apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-git
spec:
  initContainers:
    - name: git-clone
      image: alpine/git
      args:
        - clone
        - https://github.com/c1t1d0s7/startbootstrap-sb-admin-2.git
        - /repo
      volumeMounts:
        - name: git-repository
          mountPath: /repo
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: git-repository
          mountPath: /usr/share/nginx/html
  volumes:
    - name: git-repository
      emptyDir: {}
