apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: efs-deploy
  template:
    metadata:
      labels:
        app: efs-deploy
    spec:
      containers:
        - name: app
          image: ubuntu
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-pvc
