---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-sa-user1
  labels:
    app: kubectl
spec:
  serviceAccountName: sa-user1
  containers:
  - name: kubectl
    image: bitnami/kubectl:1.27.6
    command: ['sleep']
    args: ['infinity']
---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-sa-user2
  labels:
    app: kubectl
spec:
  serviceAccountName: sa-user2
  containers:
  - name: kubectl
    image: bitnami/kubectl:1.27.6
    command: ['sleep']
    args: ['infinity']
---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-sa-admin
  labels:
    app: kubectl
spec:
  serviceAccountName: sa-admin
  containers:
  - name: kubectl
    image: bitnami/kubectl:1.27.6
    command: ['sleep']
    args: ['infinity']