apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy-fg
  namespace: dev
  labels:
    app: myapp-deploy-fg
    env: fg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-deploy-fg
      env: fg
  template:
    metadata:
      labels:
        app: myapp-deploy-fg
        env: fg
    spec:
      containers:
      - name: myapp
        image: ghcr.io/c1t1d0s7/go-myweb:alpine
        ports:
        - containerPort: 8080
