apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-cm
spec:
  containers:
  - image: ghcr.io/c1t1d0s7/go-myweb:alpine
    name: myapp
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: myapp-cm-message
          key: message
    ports:
    - containerPort: 8080
      protocol: TCP
