kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-admin-admin
subjects:
- kind: ServiceAccount
  name: sa-admin
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: "rbac.authorization.k8s.io"
