kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-user1-read-pod
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-user1
  apiGroup: ""
  namespace: default
roleRef:
  kind: Role
  name: read-pod
  apiGroup: rbac.authorization.k8s.io
